version: "3.8"

services:
  iris-app:
    #image: iris-fastapi-app:latest
    image: 339712962914.dkr.ecr.us-east-1.amazonaws.com/iris-model:latest
    container_name: iris-app
    ports:
      - "8000:8000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
