# Configuration for Model Training and Evaluation
# This file defines the model configurations, data paths, and experiment settings.

data:
  raw: data/raw/iris.csv
  processed: data/processed/iris_cleaned.csv


experiment:
  name: model_comparison_experiment

model:
  type: logistic_regression   # default model used in baseline
  test_size: 0.2
  random_state: 42
  target_column: target
  registry_name: iris_best_model


# Model Configuration

models:
  logistic_regression:
    class: sklearn.linear_model.LogisticRegression
    params:
      C: 1.0
      solver: "lbfgs"
      max_iter: 200
    optuna_search_space:
      C:
        type: float
        low: 0.01
        high: 10.0
        log: true
      solver:
        type: categorical
        choices: ['liblinear', 'lbfgs']

  random_forest:
    class: sklearn.ensemble.RandomForestClassifier
    params:
      n_estimators: 100
      max_depth: 5
      min_samples_split: 2
      min_samples_leaf: 1
    optuna_search_space:
      n_estimators:
        type: int
        low: 50
        high: 200
      max_depth:
        type: int
        low: 3
        high: 20
      min_samples_split:
        type: int
        low: 2
        high: 10
      min_samples_leaf:
        type: int
        low: 1
        high: 5

  decision_tree:
    class: sklearn.tree.DecisionTreeClassifier
    params:
      max_depth: 4
      criterion: gini
    optuna_search_space:
      max_depth:
        type: int
        low: 3
        high: 20
      criterion:
        type: categorical
        choices: ['gini', 'entropy']

  svc:
    class: sklearn.svm.SVC
    params:
      C: 1.0
      kernel: "rbf"
      gamma: "scale"
    optuna_search_space:
      C:
        type: float
        low: 0.1
        high: 10.0
        log: true
      kernel:
        type: categorical
        choices: ['linear', 'rbf', 'poly']
      gamma:
        type: categorical
        choices: ['scale', 'auto']
